### ISSUE TITLE
HTML matching tag highlighting embedded w/i PHP stopped working

### ISSUE THREAD

**Issue by spchaplin** [bmewburn/intelephense#106]
Thanks for such a useful extension! I installed VS code and this extension on my laptop for a trip, and I noticed that HTML matching tags were not highlighting when embedded in a PHP file.  I tried disabling my other extensions but the problem persisted.  Then I went on my desktop where the matching tag highlighting was working w/i PHP files, and found it had stopped working there as well.  VS Code version 1.19.1 and version 0.8.4 of Intelephense are installed on each.  Any ideas would be greatly appreciated!

**Comment by bmewburn** [comment]
I'm not experiencing any issues here. Open up the extension output and see if there are any error messages. Do you get intellisense in plain PHP files?

**Comment by spchaplin** [comment]
Hi Ben,
Thanks for your response! I'm happy to provide any information that would be helpful.  In the video below I show that matching tag highlighting works in a plain html file, then I show the intellisense works in a php file.  Also, if I type in gibberish, your extension registers a "problem" in the debug console.  Finally I go into a PHP file with embedded HTML and click on some tags, and every instance of that tag is highlighted.  When I check the output in the "debug console" below, I do not see any errors.  Please let me know if you need more information, and thanks for your help!

**Comment by bmewburn** [comment]
Do you still get html completion suggestions in mixed html/php? Try opening the output tab and selecting intelephense from the drop down to see if there are errors reported there. Perhaps you did this? In the video it looked like `tasks` was selected. You could also set `"intelephense.trace.server": "messages"` and see if there are requests/responses to/from the server.

**Comment by spchaplin** [comment]
Ben, Thanks so much for your guidance.  I added "intelephense.trace.server": "messages" to settings.json, and opened a PHP file with embedded HTML.  With the output tab open and "intelephense" selected in the drop down, I started typing a function name and intellisense was working.  I clicked on html tags, and matching tag highlighting did not work.  Then I tried typing some gibberish within php tags and under the "problems" tab, intelephense reported a problem with the code.  Below is a video and also I copied the results from the "output" tab for all this below.  Thank you!

https://www.screencast.com/t/xXAywiJ4

[Trace - 1:41:33 PM] Sending request 'initialize - (0)'.
[Trace - 1:41:33 PM] Received notification 'window/logMessage'.
[Info  - 1:41:33 PM] Initialising
[Trace - 1:41:35 PM] Received notification 'window/logMessage'.
[Info  - 1:41:35 PM] Initialised in 1363 ms
[Trace - 1:41:35 PM] Received response 'initialize - (0)' in 1572ms.
[Trace - 1:41:35 PM] Sending notification 'initialized'.
[Trace - 1:41:35 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 1:41:35 PM] Sending notification 'textDocument/didOpen'.
[Trace - 1:41:35 PM] Received request 'client/registerCapability - (0)'.
[Trace - 1:41:35 PM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 1:41:35 PM] Sending request 'documentLanguageRanges - (1)'.
[Trace - 1:41:35 PM] Received response 'documentLanguageRanges - (1)' in 6ms.
[Info  - 1:41:35 PM] Indexing started.
[Trace - 1:41:35 PM] Sending request 'knownDocuments - (2)'.
[Trace - 1:41:35 PM] Received response 'knownDocuments - (2)' in 30ms.
[Info  - 1:41:35 PM] Indexing ended | 0 files | 0.59 s
[Trace - 1:41:45 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:45 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:46 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:46 PM] Sending request 'documentLanguageRanges - (3)'.
[Trace - 1:41:46 PM] Received response 'documentLanguageRanges - (3)' in 0ms.
[Trace - 1:41:47 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:41:47 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:47 PM] Sending request 'textDocument/completion - (4)'.
[Trace - 1:41:47 PM] Received response 'textDocument/completion - (4)' in 25ms.
[Trace - 1:41:47 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:47 PM] Sending request 'textDocument/completion - (5)'.
[Trace - 1:41:47 PM] Received response 'textDocument/completion - (5)' in 9ms.
[Trace - 1:41:48 PM] Sending request 'documentLanguageRanges - (6)'.
[Trace - 1:41:48 PM] Received response 'documentLanguageRanges - (6)' in 0ms.
[Trace - 1:41:48 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:48 PM] Sending request 'textDocument/completion - (7)'.
[Trace - 1:41:48 PM] Received response 'textDocument/completion - (7)' in 7ms.
[Trace - 1:41:49 PM] Sending request 'documentLanguageRanges - (8)'.
[Trace - 1:41:49 PM] Received response 'documentLanguageRanges - (8)' in 1ms.
[Trace - 1:41:49 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:41:50 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:50 PM] Sending request 'textDocument/completion - (9)'.
[Trace - 1:41:50 PM] Received response 'textDocument/completion - (9)' in 6ms.
[Trace - 1:41:50 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:50 PM] Sending request 'textDocument/completion - (10)'.
[Trace - 1:41:50 PM] Received response 'textDocument/completion - (10)' in 6ms.
[Trace - 1:41:50 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:51 PM] Sending request 'documentLanguageRanges - (11)'.
[Trace - 1:41:51 PM] Received response 'documentLanguageRanges - (11)' in 0ms.
[Trace - 1:41:52 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:41:53 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:53 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:53 PM] Sending request 'textDocument/completion - (12)'.
[Trace - 1:41:53 PM] Received response 'textDocument/completion - (12)' in 4ms.
[Trace - 1:41:53 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:53 PM] Sending request 'textDocument/completion - (13)'.
[Trace - 1:41:53 PM] Received response 'textDocument/completion - (13)' in 4ms.
[Trace - 1:41:53 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:53 PM] Sending request 'textDocument/completion - (14)'.
[Trace - 1:41:53 PM] Received response 'textDocument/completion - (14)' in 7ms.
[Trace - 1:41:54 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:54 PM] Sending request 'textDocument/completion - (15)'.
[Trace - 1:41:54 PM] Received response 'textDocument/completion - (15)' in 8ms.
[Trace - 1:41:54 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:41:54 PM] Sending request 'documentLanguageRanges - (16)'.
[Trace - 1:41:54 PM] Received response 'documentLanguageRanges - (16)' in 0ms.
[Trace - 1:41:55 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:41:56 PM] Sending request 'textDocument/hover - (17)'.
[Trace - 1:41:56 PM] Received response 'textDocument/hover - (17)' in 2ms.
[Trace - 1:41:56 PM] Sending request 'documentLanguageRanges - (18)'.
[Trace - 1:41:56 PM] Received response 'documentLanguageRanges - (18)' in 0ms.
[Trace - 1:41:56 PM] Sending request 'textDocument/hover - (19)'.
[Trace - 1:41:56 PM] Received response 'textDocument/hover - (19)' in 1ms.
[Trace - 1:41:56 PM] Sending request 'documentLanguageRanges - (20)'.
[Trace - 1:41:56 PM] Received response 'documentLanguageRanges - (20)' in 1ms.
[Trace - 1:41:57 PM] Sending request 'textDocument/hover - (21)'.
[Trace - 1:41:57 PM] Received response 'textDocument/hover - (21)' in 1ms.
[Trace - 1:41:57 PM] Sending request 'documentLanguageRanges - (22)'.
[Trace - 1:41:57 PM] Received response 'documentLanguageRanges - (22)' in 1ms.
[Trace - 1:41:58 PM] Sending request 'textDocument/documentHighlight - (23)'.
[Trace - 1:41:58 PM] Received response 'textDocument/documentHighlight - (23)' in 1ms.
[Trace - 1:41:58 PM] Sending request 'documentLanguageRanges - (24)'.
[Trace - 1:41:58 PM] Received response 'documentLanguageRanges - (24)' in 1ms.
[Trace - 1:42:01 PM] Sending request 'textDocument/hover - (25)'.
[Trace - 1:42:01 PM] Received response 'textDocument/hover - (25)' in 0ms.
[Trace - 1:42:01 PM] Sending request 'documentLanguageRanges - (26)'.
[Trace - 1:42:01 PM] Received response 'documentLanguageRanges - (26)' in 0ms.
[Trace - 1:42:01 PM] Sending request 'textDocument/hover - (27)'.
[Trace - 1:42:01 PM] Received response 'textDocument/hover - (27)' in 1ms.
[Trace - 1:42:01 PM] Sending request 'documentLanguageRanges - (28)'.
[Trace - 1:42:01 PM] Received response 'documentLanguageRanges - (28)' in 0ms.
[Trace - 1:42:02 PM] Sending request 'textDocument/hover - (29)'.
[Trace - 1:42:02 PM] Received response 'textDocument/hover - (29)' in 1ms.
[Trace - 1:42:02 PM] Sending request 'documentLanguageRanges - (30)'.
[Trace - 1:42:02 PM] Received response 'documentLanguageRanges - (30)' in 1ms.
[Trace - 1:42:02 PM] Sending request 'textDocument/documentHighlight - (31)'.
[Trace - 1:42:02 PM] Received response 'textDocument/documentHighlight - (31)' in 0ms.
[Trace - 1:42:02 PM] Sending request 'documentLanguageRanges - (32)'.
[Trace - 1:42:02 PM] Received response 'documentLanguageRanges - (32)' in 1ms.
[Trace - 1:42:05 PM] Sending request 'textDocument/hover - (33)'.
[Trace - 1:42:05 PM] Received response 'textDocument/hover - (33)' in 1ms.
[Trace - 1:42:05 PM] Sending request 'documentLanguageRanges - (34)'.
[Trace - 1:42:05 PM] Received response 'documentLanguageRanges - (34)' in 0ms.
[Trace - 1:42:05 PM] Sending request 'textDocument/hover - (35)'.
[Trace - 1:42:05 PM] Received response 'textDocument/hover - (35)' in 2ms.
[Trace - 1:42:06 PM] Sending request 'textDocument/hover - (36)'.
[Trace - 1:42:06 PM] Received response 'textDocument/hover - (36)' in 0ms.
[Trace - 1:42:06 PM] Sending request 'documentLanguageRanges - (37)'.
[Trace - 1:42:06 PM] Received response 'documentLanguageRanges - (37)' in 0ms.
[Trace - 1:42:06 PM] Sending request 'textDocument/hover - (38)'.
[Trace - 1:42:06 PM] Received response 'textDocument/hover - (38)' in 1ms.
[Trace - 1:42:06 PM] Sending request 'documentLanguageRanges - (39)'.
[Trace - 1:42:06 PM] Received response 'documentLanguageRanges - (39)' in 1ms.
[Trace - 1:42:07 PM] Sending request 'textDocument/documentHighlight - (40)'.
[Trace - 1:42:07 PM] Received response 'textDocument/documentHighlight - (40)' in 1ms.
[Trace - 1:42:07 PM] Sending request 'documentLanguageRanges - (41)'.
[Trace - 1:42:07 PM] Received response 'documentLanguageRanges - (41)' in 0ms.
[Trace - 1:42:07 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:08 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:08 PM] Sending request 'documentLanguageRanges - (42)'.
[Trace - 1:42:08 PM] Received response 'documentLanguageRanges - (42)' in 1ms.
[Trace - 1:42:09 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:09 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:09 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:09 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:42:10 PM] Sending request 'textDocument/signatureHelp - (43)'.
[Trace - 1:42:10 PM] Received response 'textDocument/signatureHelp - (43)' in 3ms.
[Trace - 1:42:10 PM] Sending request 'documentLanguageRanges - (44)'.
[Trace - 1:42:10 PM] Received response 'documentLanguageRanges - (44)' in 1ms.
[Trace - 1:42:10 PM] Sending request 'documentLanguageRanges - (45)'.
[Trace - 1:42:10 PM] Received response 'documentLanguageRanges - (45)' in 1ms.
[Trace - 1:42:11 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:43:26 PM] Sending request 'textDocument/hover - (46)'.
[Trace - 1:43:26 PM] Received response 'textDocument/hover - (46)' in 1ms.
[Trace - 1:43:26 PM] Sending request 'documentLanguageRanges - (47)'.
[Trace - 1:43:26 PM] Received response 'documentLanguageRanges - (47)' in 1ms.

**Comment by ac-perkins** [comment]
I'm experiencing the same issue. Version 1.19.1 of code and 0.8.5 of Intelephense. No HTML completion suggestions or tag highlighting in mixed html/php. I can try to provide any other information if you need any.

**Comment by bmewburn** [comment]
What OS are you guys on?

**Comment by ac-perkins** [comment]
I'm using High Sierra 10.13.2. I've tried disabling all other extensions as well as doing a complete uninstall/reinstall of VS Code and all associated settings with the same results. Current settings are fairly minimal as well:

{
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "One Dark Pro",
    "editor.tabSize": 2,
    "editor.fontSize": 14,
    "editor.colorDecorators": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "php.suggest.basic": false
}

Curiously, using the same setup on another machine I use will not recreate the issue.

**Comment by spchaplin** [comment]
Hi Ben, Thanks for your response.

On my desktop:

Windows 10 Home
Version 1709
OS Build 16299.125

Laptop is also Windows 10 Home.  I've disabled all extensions on both laptop and desktop.  On my desktop, I've removed anything not essential from settings.json, and here's what's in it:

{
  "editor.fontFamily": "Fira Code",
  "editor.fontSize": 14,
  "editor.fontLigatures": true,
  "window.zoomLevel": 1,
  "editor.wordWrap": "on",
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "php.suggest.basic": false,
  "intelephense.trace.server": "messages"
}

I turned off real-time Windows Defender antivirus protection, closed out of VS Code and restarted after taking the above steps, but the problem persists.  If you need additional info, just let me know and thanks for your efforts!

**Comment by onetrev** [comment]
I have the exact same issues. I can confirm _matching tags_ was definitely working for a good month plus since I move to using Intelephense. I know for sure because I had starting following an issue on the theme I was using about the matching tag highlighting needed to be brighter. But now, as mentioned, matching tag functionality in gone. Also, HTML completion suggestions in mixed html/php does not work either.

Unfortunately, I can't determine when / what change made this happen as I don't know exactly when it happened. I did notice it today after I upgrade my XAMPP to PHP 7.2. But if I recall correctly, neither Intelephense nor VS Code utilize your own installed PHP, so this shouldn't matter.

System details:
Windows 10 Pro
Version 1709
OS Build 16299.125
VC Code 1.19.2

NOTE: I tested also with ALL other extensions disabled and removed all custom settings, issues persists. 

Let me know anything else I can do to help troubleshoot this.

**Comment by onetrev** [comment]
Just adding a screenshot to demonstrate this is legit. :) 

![capture](https://user-images.githubusercontent.com/597601/35172145-93d7c08c-fdba-11e7-96a9-51a3a0c9d7a6.PNG)

**Comment by Rimplot** [comment]
Highlighting matching tags does not work for me either. I've installed the extension specifically for this feature, but only autocomplete works. I tried it using a simple HTML file by just changing the extension to php. All other extensions turned off, nothing special in the settings.

Windows 10 Home
Version 1709
OS Build 16299.309
VS Code 1.21.1

**Comment by bmewburn** [comment]
I can't repro this. Is `editor.occurrencesHighlight` is set to true? You could also try a different theme.

**Comment by onetrev** [comment]
I'm with @Rimplot. If it's set to a PHP file, matching tag fails. Same file set as HTML, it works. So it's not an editor or theme setting thing. But to be sure, I checked `editor.occurrencesHighlight` is enabled. And as noted above, I too tested with all other extensions disabled and the default theme. Major bummer Ben you can't reproduce. I'll keep looking for any other variable that could affect this....

Just to double check, as I noted above, not sure if it matters, but I was running PHP 7.2 with XAMPP. Not sure what @Rimplot is? I'm now on PHP 7.2.3.

![capture](https://user-images.githubusercontent.com/597601/38339505-e314875c-38b1-11e8-81dd-c81b0cecbc88.PNG)
![capture-1](https://user-images.githubusercontent.com/597601/38339506-e348f938-38b1-11e8-9b79-661760d30c09.PNG)

**Comment by Rimplot** [comment]
`editor.occurrencesHighlight` is enabled and I've just updated WAMP to version 3.1.3, PHP 7.2.4 – but I don't think that has anything to do with our problem.

**Comment by bmewburn** [comment]
Someone may have to do some debugging to shed more light on this. To do this:
1. `git clone https://github.com/bmewburn/vscode-intelephense.git`
2. `cd vscode-intelephense && npm install`
3. open folder in vscode
4. launch a debug session by pressing F5
5. put some break points in/around `middleWarePositionalRequest` in `intelephense/src/embeddedContentDocuments.ts`

What should happen when in html is
1. A request goes to the intelephense server to get highlights/completions/whatever
2. A falsey result is returned.
3. A request goes to the intelephense server to get the language ranges of the document.
4. If position of request is not php then forward request to html extensions
5. A valid highlights/completions/whatever is returned from the html extension.

**Comment by onetrev** [comment]
I can give this a shot for sure! Just need to clarify some things. I'm confused as to why I'm cloning the package and such. Can't I just open my existing installed version of Intelephense and do the debugging from there?

**Comment by Rimplot** [comment]
I might be doing something wrongly, but the code does not run, as it cannot find the module `vscode`...

```
C:\Program Files\nodejs\node.exe --inspect-brk=7790 out\src\extension.js 
Debugger listening on ws://127.0.0.1:7790/ec0a1ca7-8c8d-454a-aaae-f3cb2be686c6
Debugger attached.
module.js:540
    throw err;
    ^

Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\vscode-intelephense\out\src\extension.js:8:18)
    at Module._compile (module.js:640:14)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
Waiting for the debugger to disconnect...
```

**Comment by onetrev** [comment]
Sorry, took me a bit to get to this. But I have the same issue as Rimplot. Dang, was really hoping to help fix this! This is not my area of expertise, so just in case also attaching screenshot, as I think I setup everything as you recommended @bmewburn.

![capture](https://user-images.githubusercontent.com/597601/39037770-d9ab8e62-44c4-11e8-9f45-27dbb216f024.PNG)

**Comment by nn-hh** [comment]
---  Google Translate ---

Sorry for the ignorant question.

https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
↓
Click : Download Extension
↓
Download : bmewburn.vscode-intelephense-client-0.8.8.vsix
↓
Extract
↓
/extension/node_modules/`vscode`←Nothing

Is this environment related?
Other extensions have `vscode`.
it would not be there for something cause here?

package.json:
<pre>
    "scripts": {
        "vscode:prepublish": "tsc -p ./",
        "compile": "tsc -p ./",
        "update-vscode": "node ./node_modules/vscode/bin/install",
        "postinstall": "node ./node_modules/vscode/bin/install"
    }
</pre>

**Comment by onetrev** [comment]
@bmewburn ... Just wondering if this is something I can still help troubleshoot. Definitely frustrating this stopped working for me (and seems like a number of other people, so definitely something up). Thanks!

**Comment by Rimplot** [comment]
Yeah, if there is anything else we can help with... then I'm here too!

**Comment by scsshomugenxv** [comment]
I'm having the same issue, but this thread is somewhat misleading. HTML tag matching in vs code when the language is set to php doesn't exist by default. the issue isn't lack of tag matching, but general selection matching. Whenever I have Intellephense enabled it seems to interfere with the '"editor.selectionHighlight": true' setting.

**Comment by nn-hh** [comment]
@bmewburn v1.0.1 unsolved
Windows 10

**Comment by onetrev** [comment]
Ya same here, still not working. Would love to help fix this since _HTML request forwarding allowing for a full HTML/Javascript/CSS/PHP development experience._ is a key feature of this extension. Unfortunately for a year now we have not been enjoying the beauty of this functionality. :(
