### ISSUE TITLE
Crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by andremacola** [bmewburn/intelephense#116]
Already did clear cache and reload. It was ok last day.

The intelephense server crashed 5 times in the last 3 minutes. The server will not be restarted.

`module.js:591
    throw err;
    ^

SyntaxError: /Volumes/Data/andremacola/.vscode-insiders/extensions/bmewburn.vscode-intelephense-client-0.8.5/server/node_modules/intelephense/lib/builtInSymbols.json: Unexpected token $ in JSON at position 135926
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Data/andremacola/.vscode-insiders/extensions/bmewburn.vscode-intelephense-client-0.8.5/server/node_modules/intelephense/lib/symbolStore.js:10:24)
    at Object.<anonymous> (/Volumes/Data/andremacola/.vscode-insiders/extensions/bmewburn.vscode-intelephense-client-0.8.5/server/node_modules/intelephense/lib/symbolStore.js:669:3)
    at Module._compile (module.js:571:32)
[Error - 20:09:12] Connection to server got closed. Server will not be restarted.`

**Comment by andremacola** [comment]
Did a completely reinstall of vscode insiders and resolve the problem
