### ISSUE TITLE
[Error] Request initialize failed with message: this.send is not a function

### ISSUE THREAD

**Issue by benyaminl** [bmewburn/intelephense#145]
Hello, I get problem with the intelephense, it's out of nowhere, I don't know why, but here's some error log that I got from the console 

`ERR Request initialize failed with message: this.send is not a function: Error: Request initialize failed with message: this.send is not a function
	at new ResponseError (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate.<anonymous> (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)`

Also this

`Request shutdown failed with message: this.send is not a function: Error: Request shutdown failed with message: this.send is not a function
	at new ResponseError (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate.<anonymous> (C:\Users\Ben\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.8\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)`

The other error that occur is 

`rejected promise not handled within 1 second`

also this's the process

`
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
`

**Comment by benyaminl** [comment]
@bmewburn any update on this?

**Comment by benyaminl** [comment]
@bmewburn seems like the problem is with the index. After rebuild index, it works again
