### ISSUE TITLE
Hovering over method provided by trait creates error.

### ISSUE THREAD

**Issue by charrondev** [bmewburn/intelephense#181]
This is likely related to https://github.com/bmewburn/intelephense/issues/176 but I feel I have more concrete reproduction steps here.

## Info

VSCode version: 1.31.1
Inteliphense version: 1.0.1

## Reproduction steps

1. Use the following file contents:

```php
<?php

trait DoesThing {
    public function doThing() {
        return true;
    }
}

class SomeClass {
    use DoesThing;

    public function hello() {
        $this->doThing()
    }
}
```

2. Hover over ` $this->doThing()`

**Expected**

Hover information like in https://github.com/bmewburn/intelephense/issues/124

**Actual**

- No information is shown.
- The error console is opened.
- The follow error is provided.

```
[Error - 12:21:09 AM] TypeError: Cannot set property 'definition' of undefined
    at t.DocumentationService.<anonymous> (/Users/adamcharron/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.1/node_modules/intelephense/lib/intelephense.js:39:125428)
    at Generator.next (<anonymous>)
    at o (/Users/adamcharron/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.1/node_modules/intelephense/lib/intelephense.js:39:117666)
[Error - 12:21:09 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot set property 'definition' of undefined
  Code: -32603 
```

**Comment by bmewburn** [comment]
Thanks for the detailed report. Fixed in 1.0.2
