### ISSUE TITLE
Error on indexing files

### ISSUE THREAD

**Issue by malvf** [bmewburn/intelephense#187]
Hello, just updated to 1.01 and the indexing is not working at all, crashing as soon as the extension is loaded. Previously, it worked without problems.

Here is the stack

```
[Info  - 10:12:51] Initialising
[Info  - 10:12:51] Reading state from c:\Users\matheus.franca\AppData\Roaming\Code\User\workspaceStorage\53002fa0ba3c26b74e526036f50f4e4f\bmewburn.vscode-intelephense-client\33d5649.
[Info  - 10:12:53] Initialised in 1287 ms
[Info  - 10:12:53] Intelephense 1.0.1
[Error - 10:13:01] TypeError: Cannot read property 'parameters' of undefined
    at v.enterScope (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:290316)
    at c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:295874
    at n (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:296233)
    at t (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:293074)
    at n (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:300855)
    at t (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:293074)
    at n (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:300855)
    at c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:294159
    at n (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:294196)
    at t (c:\Users\matheus.franca\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.1\node_modules\intelephense\lib\intelephense.js:39:293074)
[Info  - 10:13:24] Indexing started.
[Info  - 10:13:24] Indexing ended. Elapsed 0s.

```

Thanks for you time.

**Comment by malvf** [comment]
Just updated to version 1.02 and the error is gone, but indexing still does not work as expected. In the 0.88 version, it would take 10 minutes to index my workspace (40k files,at least), but now it ends at 70 seconds ( the references are not working )

**Comment by bmewburn** [comment]
Are you getting intellisense? Indexing should be quicker with 1.0.2. It used to do a double pass over files for references but now just does a single pass.

**Comment by malvf** [comment]
No intellisense or at least in the files that I opened in vscode.

**Comment by peterson-umoke** [comment]
same here, only my issue #195

**Comment by bmewburn** [comment]
tracking in bmewburn/vscode-intelephense#216
