### ISSUE TITLE
Closure variable autocompletion

### ISSUE THREAD

**Issue by ilsenem** [bmewburn/intelephense#19]
Happens when trying to declare variable inside closure function. There is no error appear if closure have defined parameters.

```php
$fn = function () {
    $ // Error
};
```

```php
\array_map(function ($item) {
    $ // No error
}, $list);
```

Error message:
```
[Error - 12:25:01 PM] TypeError: Cannot read property 'filter' of undefined
    at SimpleVariableCompletion.completions (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/node_modules/intelephense/lib/completionProvider.js:319:40)
    at CompletionProvider.provideCompletions (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/node_modules/intelephense/lib/completionProvider.js:228:36)
    at Object.provideCompletions (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/node_modules/intelephense/lib/intelephense.js:107:35)
    at handleRequest (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/server.js:82:59)
    at handleRequest (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/server.js:155:17)
    at connection.onCompletion (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/server.js:81:16)
    at handleRequest (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/node_modules/vscode-jsonrpc/lib/main.js:237:37)
    at process.callback (/home/user/.vscode/extensions/bmewburn.vscode-intelephense-client-0.6.9/server/node_modules/vscode-jsonrpc/lib/main.js:483:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
```

**Comment by bmewburn** [comment]
Thanks for the report
