### ISSUE TITLE
error when indexing files

### ISSUE THREAD

**Issue by mxmihai** [bmewburn/intelephense#190]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::DecodeWrite
 2: node::get_builtin_module
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::FatalProcessOutOfMemory
 5: v8::internal::Heap::MaxHeapGrowingFactor
 6: v8::internal::ItemParallelJob::Run
 7: v8::internal::StoreBuffer::StoreBufferOverflow
 8: v8::internal::StoreBuffer::StoreBufferOverflow
 9: v8::internal::StoreBuffer::StoreBufferOverflow
10: v8::internal::StoreBuffer::StoreBufferOverflow
11: v8::internal::StoreBuffer::StoreBufferOverflow
12: 000002A4A8904481

<--- Last few GCs --->

[15524:0000020D0EF1EDE0]   669294 ms: Mark-sweep 2034.4 (2080.6) -> 2034.4 (2080.6) MB, 3541.5 / 0.0 ms  allocation failure GC in old space requested
[15524:0000020D0EF1EDE0]   672856 ms: Mark-sweep 2034.4 (2080.6) -> 2034.4 (2079.6) MB, 3561.8 / 0.0 ms  last resort GC in old space requested
[15524:0000020D0EF1EDE0]   676270 ms: Mark-sweep 2034.4 (2079.6) -> 2034.4 (2079.6) MB, 3413.6 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002A4A8904481]
Security context: 000002244D6A5709 <JSObject>
    1: fromString [c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\intelephense\lib\intelephense.js:~39] [pc=000002A4A8F9F0B5](this=00000243E61B4A01 <Object map = 00000094293F3D61>,e=0000029FF2D38F31 <String[3]: xme>)
    2: C(aka C) [c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node...

[Info  - 9:34:32 PM] Connection to server got closed. Server will restart.
[Error - 9:34:32 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (c:\Users\mihai\.vscode\extensions\bmewburn.vscode-intelephense-client-1.0.2\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 9:34:32 PM] Request textDocument/definition failed.

**Comment by bmewburn** [comment]
duplicate bmewburn/vscode-intelephense#179
