### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by vinioo** [bmewburn/intelephense#196]
After updating to version 1.0.0+ , i'm getting the error 
"TypeError: Cannot read property 'value' of undefined"

`   at t (/home/vinicius/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.0/node_modules/intelephense/lib/intelephense.js:39:293074)
    at /home/vinicius/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.0/node_modules/intelephense/lib/intelephense.js:39:293176
    at n (/home/vinicius/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.0/node_modules/intelephense/lib/intelephense.js:39:293210)
    at Object.e.transform (/home/vinicius/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.0/node_modules/intelephense/lib/intelephense.js:39:325549)
[Error - 10:33:52] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'value' of undefined
  Code: -32603 `

**Comment by SparK-Cruz** [comment]
Same here, other var though...
```
[Error - 3:56:04 PM] TypeError: Cannot read property 'kind' of undefined
    at A.canSuggest (/home/roger/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.2/node_modules/intelephense/lib/intelephense.js:39:195057)
    at t.CompletionProvider.provideCompletionItems (/home/roger/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.2/node_modules/intelephense/lib/intelephense.js:39:163631)
    at t.Intelephense.<anonymous> (/home/roger/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.2/node_modules/intelephense/lib/intelephense.js:39:157553)
    at Generator.next (<anonymous>)
    at o (/home/roger/.vscode/extensions/bmewburn.vscode-intelephense-client-1.0.2/node_modules/intelephense/lib/intelephense.js:39:152757)
[Error - 3:56:04 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'kind' of undefined
  Code: -32603 
```

**Comment by bmewburn** [comment]
Please upgrade to 1.0.3. If there's still an issue please submit at https://github.com/bmewburn/vscode-intelephense
