### ISSUE TITLE
TypeError: Cannot read property 'baseClause' of undefined

### ISSUE THREAD

**Issue by jolusadev** [bmewburn/intelephense#37]
After the last update I have got this error:

[Info - 20:25:36] Initialising
[Info - 20:25:37] Initialised in 928 ms
[Info - 20:25:38] Indexing started.
[Error - 20:25:43] TypeError: Cannot read property 'baseClause' of undefined
at NameResolverVisitor._anonymousClassDeclaration (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\nameResolverVisitor.js:71:24)
at NameResolverVisitor.preorder (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\nameResolverVisitor.js:27:54)
at SymbolReader.preorder (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:255:49)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:126:31)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
[Error - 20:25:43] TypeError: Cannot read property 'baseClause' of undefined
at NameResolverVisitor._anonymousClassDeclaration (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\nameResolverVisitor.js:71:24)
at NameResolverVisitor.preorder (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\nameResolverVisitor.js:27:54)
at SymbolReader.preorder (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:255:49)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:126:31)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
at TreeTraverser._traverse (C:\Users\jlcal.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.0\server\node_modules\intelephense\lib\types.js:134:22)
[Info - 20:25:55] Indexing ended | 10185 files | 16.948 s

**Comment by bmewburn** [comment]
Thanks for the report, will publish a fix shortly
