### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by anedisi** [bmewburn/intelephense#52]
Im getting those errors in my console when im editing php files, and the methods of the class should be shown.

    RangeError: Maximum call stack size exceeded

something like this

    SomeClass::

and now my console is open and the error is shown

Im not sure what else could i submit to get you a better idea.

https://www.dropbox.com/s/l5vviy4pwbbkjf6/Screenshot%202017-09-01%2009.46.36.png?dl=0

**Comment by bmewburn** [comment]
Thanks for reporting. Looks like it's something to do with resolving the type of a variable.

**Comment by Fenweldryn** [comment]
I'm getting the same error. Seems like it can't proccess that much files, but why is it processing all php files? I have only 2 open atm.

`[Info  - 09:34:46] Initialising
[Info  - 09:34:48] Initialised in 1886 ms
[Info  - 09:34:51] Indexing started.
[Info  - 09:35:00] Indexing ended | 2473 files | 8.870 s
[Error - 09:36:18] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
[Error - 09:36:19] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
[Error - 09:36:20] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
[Error - 09:36:22] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser.traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:38:14)
    at Context.get variableTable [as variableTable] (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\context.js:219:23)
    at SimpleVariableCompletion.completions (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\completionProvider.js:380:31)
[Error - 09:36:23] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser.traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:38:14)
    at Context.get variableTable [as variableTable] (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\context.js:219:23)
    at SimpleVariableCompletion.completions (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\completionProvider.js:380:31)
[Error - 09:36:24] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser.traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:38:14)
    at Context.get variableTable [as variableTable] (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\context.js:219:23)
    at SimpleVariableCompletion.completions (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\completionProvider.js:380:31)
[Error - 09:36:29] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser.traverse (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:38:14)
    at Context.get variableTable [as variableTable] (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\context.js:219:23)
    at SimpleVariableCompletion.completions (C:\Users\kkfv\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\completionProvider.js:380:31)`

**Comment by anedisi** [comment]
it happened today again, so it looks like its reaching a limit inside typeString merge because for some reason the parts array is full of array types, and fn.applay reaches javascript limit.

I got this when i put a console.log inside a merge method.

`        console.log("is type", type);
        let parts = util.isString(type) ? this._chunk(type) : type._parts;
        Array.prototype.push.apply(parts, this._parts);`


`is type TypeString {
  _parts: 
   [ 'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     'array',
     ... 130972 more items ] }
[Error - 13:54:14] RangeError: Maximum call stack size exceeded`

and the reason is it looks like that in the file that i opened there was a same variable name
used 2 times with array_diff,
after changind the variable name so the names are different i dont get the error any more.

**Comment by bmewburn** [comment]
Thanks for the further info @anedisi .There's some kind of infinite loop/recursion there. This part of the code has had a big refactor in upcoming version. Are you able to share a small code snippet that caused this so I can make sure it gets resolved?

**Comment by Manusan42** [comment]
Sadly I cannot use the extension at all, because I get the 
```
[Error - 15:51:37] RangeError: Maximum call stack size exceeded
    at TypeString.merge (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeString.js:61:30)
    at VariableTable._mergeSets (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:546:83)
    at VariableTable.pruneBranches (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\typeResolver.js:296:36)
    at VariableTypeResolver.postorder (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:273:22)
    at TreeTraverser._traverse (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:142:21)
    at TreeTraverser._traverse (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
    at TreeTraverser._traverse (C:\Users\Manusan\.vscode\extensions\bmewburn.vscode-intelephense-client-0.7.2\server\node_modules\intelephense\lib\types.js:134:22)
```
after nearly each typed `$`-symbol. Then I need to reload the window and it happens again after one or two typed variables. 
But I have to say, I'am working on a pretty big project with multiple hundred files and many of them have more than thousand lines of code.

Thus the error only occures if I'm working at large files and at deep levels.

**Comment by anedisi** [comment]
@bmewburn i will try to recreate it this week and then submit that file.

**Comment by bmewburn** [comment]
This part of the code has been refactored out in v0.8.0. Can reopen if still a problem.
