### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by cyrus86** [bmewburn/intelephense#54]
Happened upon undo delete line within a php comment block.
```
[Info  - 11:30:26 AM] Initialising
[Info  - 11:30:28 AM] Initialised in 1967 ms
[Info  - 11:30:28 AM] Indexing started.
[Info  - 11:30:28 AM] Indexing ended | 2 files | 0.22 s
[Error - 8:20:44 AM] TypeError: Cannot read property 'slice' of undefined
    at ContextVisitor.get spine [as spine] (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/context.js:45:27)
    at ContextResolver.get spine [as spine] (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/context.js:21:36)
    at new Context (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/context.js:103:46)
    at DefinitionProvider.provideDefinition (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/definitionProvider.js:18:23)
    at Object.provideDefinition (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/intelephense.js:113:35)
    at handleRequest (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/server.js:117:44)
    at handleRequest (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/server.js:180:17)
    at connection.onDefinition (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/server.js:116:12)
    at handleRequest (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/vscode-jsonrpc/lib/main.js:352:27)
    at processMessageQueue (/Users/d71298/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/vscode-jsonrpc/lib/main.js:243:17)
```

**Comment by robindrost** [comment]
Try to increase the setting of maxSetting:

"intelephense.file.maxSize": 10000000,

**Comment by bmewburn** [comment]
This part of the code has been refactored out in v0.8.0. Can reopen if there's still a problem here.
