### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by IIInsomnia** [bmewburn/intelephense#55]
[Error - 20:10:41] RangeError: Maximum call stack size exceeded
    at TypeString.merge (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/typeString.js:61:30)
    at VariableTable._mergeSets (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/typeResolver.js:546:83)
    at VariableTable.pruneBranches (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/typeResolver.js:521:18)
    at VariableTypeVisitor.postorder (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/typeResolver.js:296:36)
    at VariableTypeResolver.postorder (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:273:22)
    at TreeTraverser._traverse (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:142:21)
    at TreeTraverser._traverse (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:134:22)
    at TreeTraverser._traverse (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:134:22)
    at TreeTraverser._traverse (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:134:22)
    at TreeTraverser._traverse (/Users/shenghui/.vscode/extensions/bmewburn.vscode-intelephense-client-0.7.2/server/node_modules/intelephense/lib/types.js:134:22)

**Comment by bmewburn** [comment]
Tracking in #52
