### ISSUE TITLE
`(new ClassName())->...` autocompletion error

### ISSUE THREAD

**Issue by tehSLy** [bmewburn/intelephense#72]
When I was trying to get an autocompletion on construction like `$params = (new \ReflectionMethod(__CLASS__, '__construct'))->...` this triggered an error, listed below.
```[Error - 15:16:58] onCompletion | file:///c%3A/main/dev/Ampps/www/app/core/classes/DTO/product.php | {"line":19,"character":63}
Error: Invalid Argument
    at ObjectAccessCompletion._toCompletionItem (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\intelephense\lib\completionProvider.js:680:23)
    at ObjectAccessCompletion.completions (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\intelephense\lib\completionProvider.js:586:29)
    at CompletionProvider.provideCompletions (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\intelephense\lib\completionProvider.js:160:36)
    at Object.provideCompletions (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\intelephense\lib\intelephense.js:282:35)
    at handleRequest (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\server.js:153:55)
    at handleRequest (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\server.js:241:17)
    at connection.onCompletion (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\server.js:152:12)
    at handleRequest (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\vscode-jsonrpc\lib\main.js:361:27)
    at processMessageQueue (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\vscode-jsonrpc\lib\main.js:252:17)
    at Immediate.<anonymous> (C:\Users\anybody\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\server\node_modules\vscode-jsonrpc\lib\main.js:242:13)```

**Comment by bmewburn** [comment]
Resolved in v0.8.2
