### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by marcodevsquad** [bmewburn/intelephense#82]
First of all congratulations for this awesome VSCode extension! You are doing a great job!

I'm getting this error in the output:

```
[Info  - 07:54:07] Indexing started.
[Error - 07:55:52] onDiscoverReferences | file:///home/marco/Projects/mked/vendor/phploc/phploc/tests/_files/issue_139.php
TypeError: Cannot read property 'name' of undefined
    at NameResolver.matchImportedSymbol (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/nameResolver.js:82:18)
    at NameResolver._resolveUnqualified (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/nameResolver.js:98:22)
    at NameResolver.resolveNotFullyQualified (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/nameResolver.js:59:18)
    at QualifiedNameTransform.push (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/referenceReader.js:1067:54)
    at ReferenceReader.postorder (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/referenceReader.js:329:29)
    at TreeTraverser._traverse (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/types.js:177:21)
    at TreeTraverser._traverse (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/types.js:169:22)
    at TreeTraverser._traverse (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/types.js:169:22)
    at TreeTraverser._traverse (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/types.js:169:22)
    at TreeTraverser._traverse (/home/marco/.vscode/extensions/bmewburn.vscode-intelephense-client-0.8.2/server/node_modules/intelephense/lib/types.js:169:22)
[Info  - 07:56:26] Indexing ended | 10504 files | 139.144 s
```

I'm not sure when this started to happen, but **_maybe_** it started after I upgrade the vscode version.

Any ideas?

I'm using a composer project with Laravel 5.4.

Thanks!

**Comment by scottsb** [comment]
Seeing the same thing here with a Magento 2 project.

**Comment by bmewburn** [comment]
Thanks for reporting. You can exclude all vendor tests as a workaround. 
`"files.exclude":["vendor/**/tests":true, "vendor/**/Tests":true]`
