### ISSUE TITLE
error, it stops working. always

### ISSUE THREAD

**Issue by zero2000** [bmewburn/intelephense#84]
hello I am a conforming user or it was of this extension, when I use it in project supposedly load all necessary lon to work but or surprise, nothing and here I have the debug as evidence to help them to see the faul 

`
[Error - 19:51:56] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (C:\Users\DESARROLLO-PERCY\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Socket.<anonymous> (internal/child_process.js:342:11)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
[Info  - 19:51:57] Initialising
[Info  - 19:51:59] Initialised in 1070 ms

`

**Comment by bmewburn** [comment]
Is there a particular file you try to view document symbols for that always crashes? If you could provide a minimal working example of this file I could investigate further.

**Comment by zero2000** [comment]
at first I thought it was in some files, but then I got the surprise that it is with everyone, supposedly loads all the dependencies that use the excitement but then it does not work at all, it's as if I gave him a stroke

**Comment by bmewburn** [comment]
The error above concerns the connection unexpectedly closing but does not indicate what caused the connection to the language server to close. I'd need further information to investigate further.
